name: CI - Testes de API (Mocha/K6)

on:
  push:
    branches: [ "main", "master" ] # Roda automaticamente em cada push
  pull_request:
    branches: [ "main", "master" ] # Roda em cada Pull Request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' 

      - name: Instalando as dependencias
        run: npm install

      # 1. INICIAR O SERVIDOR DE APLICAÇÃO
      # O servidor precisa estar rodando para os testes de integração se conectarem.
      - name: Iniciar o Servidor de Aplicacao
        # O comando 'npm start' ou 'npm run server' deve iniciar sua API.
        # O '&' é essencial para rodar em background.
        run: npm start & 
        # Se você usa 'npm run server', troque o comando acima.

      # 2. RODAR TESTES DE INTEGRAÇÃO (Mocha/Chai/Supertest)
      - name: Executar Testes de Integracao (Mocha/Supertest)
        # Este comando deve ser o que você usa para rodar seus testes de integração.
        # Exemplo: 'npm test' ou 'mocha'
        run: npm test 

      # 3. RODAR TESTES DE PERFORMANCE (K6)
      # Se o K6 estiver instalado globalmente ou via npm, este comando funciona.
      - name: Executar Todos os Testes de Performance (K6)
        run: k6 run tests/testk6/run_all_k6.js
    
      
